version: '2'
services:
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: censo
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres